### ISSUE TITLE
Searchmanager (ES) should support CORS

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass-services#14]
At the moment Elasticsearch does not support CORS out-of-the-Box. There should be some instructions how to enable this.

**Comment by smouzakitis** [comment]
Hi Fabian,

Many thanks for the issue.For enabling CORS, one can go to the elastic search server configuration file (<elastic search folder/config/elasticsearch.yml) and add the following line:
http.cors.enabled: true

Do you want me to include this somewhere? Since this is more a server setting issue, and not a searchmanager issue i am not sure where to include this information.

thanks,
Spiros

**Comment by FabiApfelkern** [comment]
I am not sure how to handle it. My goal is to get rid of the proxy in the server.js. So local development will also rely on CORS. I guess the best way is to provide an elasticsearch.yml in the Services repo and add instructions how to deploy that config locally.
